feat(main): implemented endpoint with information about user
dreyliky/angular-community-ua-backend pull request #45
Opened 2023-03-07 17:33 UTC by br1ttan

2023-03-07 20:10 UTC, br1ttan commented
де мені описати _id?

2023-03-07 20:46 UTC, dreyliky requested changes

2023-03-07 20:46 UTC, dreyliky commented on apps/main/src/user/adapters/response-to-user-dto.adapter.ts
> +export function UserResponseToUserDto(user: User): UserDto {
```suggestion
export function adaptUserToUserDto(user: User): UserDto {
```

2023-03-07 20:46 UTC, dreyliky commented on apps/main/src/user/jwt-strategy.ts
> +            secretOrKey: process.env.JWT_TOKEN_SECRET
ConfigService для роботи з env

2023-03-07 20:46 UTC, dreyliky commented on apps/main/src/user/users.service.ts
> +            throw new UnauthorizedException('User not found');
Має бути 404 NotFoundException

2023-03-07 20:46 UTC, dreyliky commented on apps/main/src/user/users.service.ts
> +        if (!userResponse) {
Якщо в response масив, значить треба перевіряти чи є там елемент якийсь. Сам масив буде завжди

2023-03-10 18:42 UTC, dreyliky approved these changes

2023-03-10 18:43 UTC, merged