Move user and token logic to a separate Microservices
dreyliky/angular-community-ua-backend pull request #47
Opened 2023-03-28 19:28 UTC by AndreyBuvria

M-TOKEN Environment:
`PORT=5001
MONGO_URL="mongodb://161.35.70.152:27017"
MONGO_USER="superadmin"
MONGO_PASSWORD="0KuQjLbfG36"
MONGO_DB="acua-dev"
JWT_TOKEN_SECRET=Z1yX2nxf9V1h&u1trkA6cDia6RUQWmnQe26B
ENCRYPTION_SECRET=Xh89FHtova80!Qe3%1
`

M-USER Environment:
`PORT=5002
MONGO_URL="mongodb://161.35.70.152:27017"
MONGO_USER="superadmin"
MONGO_PASSWORD="0KuQjLbfG36"
MONGO_DB="acua-dev"
`

2023-04-01 11:35 UTC, dreyliky commented
AuthGuard винести в shared;
Module для кожного Microservice в shared з forRoot методом, який провайдить токен мікросервісу;
В package json додати команди для запуску проєктів разом з залежними мікросервісами;
Оновити readme - додати інфу про запуск проєктів;

2023-04-07 19:07 UTC, dreyliky requested changes

2023-04-07 19:07 UTC, dreyliky commented on apps/m-user/src/m-user.module.ts
> +export class MUserModule {}
Давай перейменуємо головні модулі на `app.module`. Сервіс і контроллер можна назвати просто `UserService` & `UserController`

2023-04-07 19:07 UTC, dreyliky commented on libs/shared/src/providers/m-token.provider.ts
> +    provide: 'M-TOKEN',
Давай зробимо константи для рядку який ми провайдимо як токен. Також, пропоную назвати її: `const TOKEN_MICROSERVICE = 'TOKEN-MICROSERVICE';`

2023-04-07 19:07 UTC, dreyliky commented on libs/shared/src/providers/m-user.provider.ts
> +                host: '0.0.0.0',
Хардкодний хост виглядає сумнівно. Думаю, варто його винести в env

2023-04-07 19:07 UTC, dreyliky commented on apps/code-review/src/review-request/guards/auth.guard.ts
> +    ExecutionContext, Inject, Injectable, UnauthorizedException
Enters

2023-04-07 19:07 UTC, dreyliky commented on apps/code-review/src/review-request/services/review-request.service.ts
> +        private mUserClient: ClientProxy
Давай перейменуємо всюди такі назви полів, замість цього будемо називати їх: `userMicroservice` або `tokenMicroservice` замість `mUserClient`

2023-04-07 19:07 UTC, dreyliky commented on apps/code-review/src/review-request/services/review-request.service.ts
> +            this.mUserClient.send('adapt_user_to_dto_one', dataDocument.user)
Необхідно повиносити назви команд в Enum чи щось подібне.

Щось типу:
```
enum UserMicroserviceCmd {
    AdaptUserToDto = 'adapt_user_to_dto_one',
    ...
}
```

Такі єнами можна в Shared винести і в мікросервісах також їх підрубити

2023-04-07 19:07 UTC, dreyliky commented on apps/m-token/src/m-token.controller.ts
> +    constructor(private readonly mTokenService: MTokenService) {}
Просто `tokenService` як поле так і клас. І так з усіма подібними місцями

2023-04-07 19:07 UTC, dreyliky commented on apps/code-review/src/app.module.ts
> +
Зайвий ентер

2023-04-08 11:13 UTC, AndreyBuvria commented
Було додано до .env MAIN та CODE-REVIEW проектів: 
`M_TOKEN_HOST="0.0.0.0"
M_USER_HOST="0.0.0.0"
M_TOKEN_PORT=5001
M_USER_PORT=5002`

Вирішив краще просто замінити харкордні рядки патернів мікросервісів на enum, бо не дуже бачу сенсу все ускладнювати і робити обгортку над `ClientProxу`, у випадку `send` метода.

2023-04-10 13:35 UTC, dreyliky requested changes

2023-04-10 13:35 UTC, dreyliky commented on apps/code-review/src/app.module.ts
> +            host: process.env['M_USER_HOST'],
Хардкодні рядки, варто замінити на enum. А також, нехай модуль всередині себе бере ці env variables. Як це робить MongooseModule

2023-04-10 13:35 UTC, dreyliky commented on apps/code-review/src/review-request/models/code-review-request.dto.ts
> +import { ServiceUserDto } from '@acua/shared';
Для чого префікс "Service"? Мені здається без нього буде логічніше.

А от щодо `@acua/shared/user` шляху який був, ідея була в тому щоб не колізили різні назви які експортуються з різних сутностей. То ж пропоную повернути це

2023-04-10 13:35 UTC, dreyliky commented on apps/code-review/src/review-request/review-request.controller.ts
> +    ): Promise<unknown> {
Чому `unknown`?

2023-04-10 13:35 UTC, dreyliky commented on apps/code-review/src/review-request/review-request.module.ts
> +import { User, UserSchema } from 'apps/user/src/schemas';
Не треба імпортувати щось з іншого проєкту

2023-04-10 13:35 UTC, dreyliky commented on apps/code-review/src/review-request/review-request.module.ts
> +            { name: User.name, schema: UserSchema },
Для чого це тут? CodeReview не має працювати з юзером в базі. Для цього є мікросервіс user

2023-04-10 13:35 UTC, dreyliky commented on apps/user/src/main.ts
> +                host: '0.0.0.0',
Хардкодний HOST

2023-04-10 13:35 UTC, dreyliky commented on apps/token/src/app.service.ts
> +        if (bearerToken && bearerToken.split(' ')[0] === 'Bearer') {
Давай будемо викликати split 1 раз і запишемо результат в const щоб заюзати в двох цих місцях.

Перевірка if (bearerToken) це не задача цього методу, а задача коду який буде викликати цей метод

2023-04-10 13:35 UTC, dreyliky commented on apps/token/src/main.ts
> +                host: '0.0.0.0',
Хардкодний HOST

2023-04-10 13:35 UTC, dreyliky commented on apps/token/src/app.service.ts
> +    public async verify(token: string | null): Promise<any> {
```suggestion
    public async verify(token: string): Promise<void> {
```

2023-04-10 13:35 UTC, dreyliky commented on apps/main/src/login/login-via-telegram.service.ts
> +        USER_MICROSERVICE_TOKEN,
Ми не можемо просто робити `@Inject(USER_MICROSERVICE)` в конструкторі?

2023-04-10 13:35 UTC, dreyliky commented on libs/shared/src/modules/user-microservice/user-microservice.data.ts
> +export const USER_MICROSERVICE_TOKEN = 'USER_MICROSERVICE';
```suggestion
export const USER_MICROSERVICE = 'USER_MICROSERVICE';
```

2023-04-10 13:35 UTC, dreyliky commented on libs/shared/src/modules/token-microservice/token-microservice.data.ts
> +export const TOKEN_MICROSERVICE_TOKEN = 'TOKEN_MICROSERVICE';
```suggestion
export const TOKEN_MICROSERVICE = 'TOKEN_MICROSERVICE';
```

2023-04-10 13:38 UTC, dreyliky requested changes

2023-04-10 13:38 UTC, dreyliky commented on apps/token/src/app.controller.ts
> +    constructor(private readonly mTokenService: AppService) {}
Давай приберемо з усіх місць префікси "m"

2023-04-12 23:55 UTC, AndreyBuvria commented on apps/main/src/login/login-via-telegram.service.ts
> +        USER_MICROSERVICE_TOKEN,
Ні, бо як ти казав DI працює трохи інакше, через constructor based dependency воно буде шукати залежність тільки в межах цього модуля, тому юзається `ModuleRef` обовʼязково з `strict = true`

2023-04-13 00:12 UTC, AndreyBuvria commented on apps/code-review/src/review-request/review-request.module.ts
> +import { User, UserSchema } from 'apps/user/src/schemas';
Згоден але виносити ці сутності в shared теж не дуже вірно...

2023-04-13 00:14 UTC, AndreyBuvria commented on apps/code-review/src/review-request/review-request.module.ts
> +import { User, UserSchema } from 'apps/user/src/schemas';
Згоден, але виносити ці сутності в shared теж не дуже вірно...

2023-04-13 00:19 UTC, AndreyBuvria commented on apps/code-review/src/review-request/review-request.controller.ts
> +    ): Promise<unknown> {
Бо дані response ніяк не серіалізуються/адаптуються до dto моделі.
Також я думаю, що в цьому випадку для відповіді POST запиту не є обовʼязковим поверненням деяких цільних даних з створеного документу...

2023-04-16 19:43 UTC, dreyliky approved these changes

2023-04-16 19:48 UTC, merged